MCQ_SETS = ["1", "2", "5", "10", "15"]


GOOG_LANG = [
"Afrikaans - af",
"Albanian - sq",
"Amharic - am",
"Arabic - ar",
"Armenian - hy",
"Azerbaijani - az",
"Basque - eu",
"Belarusian - be",
"Bengali - bn",
"Bosnian - bs",
"Bulgarian - bg",
"Catalan - ca",
"Cebuano - ceb",
"Chinese Simplified - zh-CN or zh BCP-47",
"Chinese Traditional - zh-TW BCP-47",
"Corsican - co",
"Croatian - hr",
"Czech - cs",
"Danish - da",
"Dutch - nl",
"English - en",
"Esperanto - eo",
"Estonian - et",
"Filipino Tagalog - fil",
"Finnish - fi",
"French - fr",
"Frisian - fy",
"Galician - gl",
"Georgian - ka",
"German - de",
"Greek - el",
"Gujarati - gu",
"Haitian Creole - ht",
"Hausa - ha",
"Hawaiian - haw",
"Hebrew - he or iw",
"Hindi - hi",
"Hmong - hmn",
"Hungarian - hu",
"Icelandic - is",
"Igbo - ig",
"Ilocano - ilo",
"Indonesian - id",
"Irish - ga",
"Italian - it",
"Japanese - ja",
"Javanese - jv or jw",
"Kannada - kn",
"Kazakh - kk",
"Khmer - km",
"Kinyarwanda - rw",
"Korean - ko",
"Kurdish - ku",
"Kyrgyz - ky",
"Lao - lo",
"Latin - la",
"Latvian - lv",
"Lithuanian - lt",
"Luganda - lg",
"Luxembourgish - lb",
"Macedonian - mk",
"Malagasy - mg",
"Malay - ms",
"Malayalam - ml",
"Maltese - mt",
"Maori - mi",
"Marathi - mr",
"Mongolian - mn",
"Myanmar Burmese - my",
"Nepali - ne",
"Norwegian - no",
"Nyanja Chichewa - ny",
"Odia Oriya - or",
"Pashto - ps",
"Persian - fa",
"Polish - pl",
"Portuguese Portugal, Brazil - pt",
"Punjabi - pa",
"Romanian - ro",
"Russian - ru",
"Samoan - sm",
"Scots Gaelic - gd",
"Sepedi - nso",
"Serbian - sr",
"Sesotho - st",
"Shona - sn",
"Sindhi - sd",
"Sinhala Sinhalese - si",
"Slovak - sk",
"Slovenian - sl",
"Somali - so",
"Spanish - es",
"Sundanese - su",
"Swahili - sw",
"Swedish - sv",
"Tagalog Filipino - tl",
"Tajik - tg",
"Tamil - ta",
"Tatar - tt",
"Telugu - te",
"Thai - th",
"Turkish - tr",
"Turkmen - tk",
"Ukrainian - uk",
"Urdu - ur",
"Uyghur - ug",
"Uzbek - uz",
"Vietnamese - vi",
"Welsh - cy",
"Xhosa - xh",
"Yiddish - yi",
"Yoruba - yo",
"Zulu - zu",
]

QUESTION_MODE = ["Standard", "Reversed"]